version: '3.8'

services:
  task-management-front:
    container_name: task-management-front
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:4173"
    environment:
      - VITE_HOST_API=${VITE_HOST_API}
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge